DATA:
  DATASET: "ilsvrc2012"
  DIR: "/media/data2/dataset/ilsvrc12/"
  BS: 256
  NUM_CLASSES: 1000

MODEL:
  MODEL: "resnet34"

OPTIMIZER:
  TYPE: adam
  WEIGHT_DECAY: 0.0001
  LR: 0.1
  GAMMA: 0.1
  MOMENTUM: 0.9
  WARMUP_EPOCHS: 0
  EPOCHS: 120

CUDA:
  CUDA: True
  GPU_ID: 0
  DATA_PARALLEL: True

VISDOM:
  VISDOM: True
  PORT: 8097

MISC:
  LOGFREQ: 20
  TMP: "tmp/tmp"
  RAND_SEED: 7

