DATA:
  DATASET: "cifar100"
  DIR: "/home/kai/.torch/data"
  BS: 256
  NUM_CLASSES: 100

MODEL:
  MODEL: "resnet.resnet18"

OPTIMIZER:
  TYPE: SGD
  WEIGHT_DECAY: 0.0001
  LR: 0.1
  GAMMA: 0.1
  MOMENTUM: 0.9
  WARMUP_EPOCHS: 0
  EPOCHS: 350
  MILESTONES: [150, 250]

CUDA:
  CUDA: True
  GPU_ID: 0
  DATA_PARALLEL: True

VISDOM:
  VISDOM: True
  PORT: 8097

MISC:
  LOGFREQ: 20
  TMP: "" # automatically deternined by dataset and model name
  RAND_SEED: 7

